[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimize = true
optimizer_runs = 2000000000000000000

remappings = ["forge-std/=lib/forge-std/src/",
"@openzeppelin/=lib/openzeppelin-contracts/",
"diamond-std/=lib/diamond-std/",]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
