[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = "0.8.28"
optimize = true
optimizer_runs = 2000000000

evm_version = "prague"

remappings = [
    "@openzeppelin/=dependencies/@openzeppelin-contracts-5.3.0/",
    "diamond-std/=lib/diamond-std/",
    "forge-std/=dependencies/forge-std-1.9.7/",
    "safe-smart-account-v1.4.1/=dependencies/safe-smart-account-v1.4.1/",
    "safe-smart-account/=dependencies/safe-smart-account-1.4.1/contracts/",
]

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_prefix = ""
remappings_location = "config"
recursive_deps = false

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"
safe-smart-account = { version = "v1.4.1", git = "git@github.com:safe-global/safe-smart-account.git", branch = "release/v1.4.1" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
