name: Composite Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

permissions:
  pull-requests: write

jobs:
  test:
    uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/workflows/onchain-build-test-report.yaml@v0.0.3
    secrets: inherit
