name: Generate Gas Report

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test"]
    types: [completed]

jobs:
  check-all-workflows:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check workflow statuses
        id: check-workflows
        run: |
          # Wait for a reasonable time for other workflows to complete
          sleep 200
          
          # Use GitHub API to check status of all required workflows
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          SHA="${{ github.event.workflow_run.head_sha }}"
          
          # Check each required workflow
          REQUIRED_WORKFLOWS=("Test" "Check Markdown links" "Code coverage evaluation" "Contract Size")
          ALL_SUCCEEDED=true
          
          for workflow in "${REQUIRED_WORKFLOWS[@]}"; do
            echo "Checking status of workflow: $workflow"
            STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/*/runs?head_sha=$SHA&event=pull_request" | \
              jq --arg name "$workflow" '.workflow_runs[] | select(.name==$name) | .conclusion')
            
            echo "$workflow status: $STATUS"
            if [[ "$STATUS" != *"success"* ]]; then
              ALL_SUCCEEDED=false
              echo "$workflow is not successfully completed"
            fi
          done
          
          # Set output variable for next job
          echo "all_succeeded=$ALL_SUCCEEDED" >> $GITHUB_OUTPUT
          
          if [ "$ALL_SUCCEEDED" = false ]; then
            echo "Not all required workflows have completed successfully"
            exit 1
          fi
  gas-report:
    # Only run if all prerequisite workflows succeeded
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
        # Checkout the actual commit that triggered the workflow run
        ref: ${{ github.event.workflow_run.head_sha }}

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v1.2.1

    - name: Install python dependencies for tests
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt
        forge soldeer install

    - name: Build the repository
      run: forge build

    - name: Generate latest gas report
      run: |
        bash script/reportGas.sh -v

    - name: Create timestamped archive
      run: |
        TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
        COMMIT_HASH=$(git rev-parse --short HEAD)
        cp gasReports/GAS_USAGE.md "gasReports/archive/gas-report_${TIMESTAMP}_${COMMIT_HASH}.md"

    - name: Commit gas reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gasReports/
        if ! git diff --staged --quiet; then
          git commit -m "📊 Update gas reports for merge $(git rev-parse --short HEAD) [skip ci]"
          git push
        fi
