name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test
        id: build-and-test
        uses: Forte-Service-Company-Ltd/application-infrastructure/.github/actions/onchain-build-and-test@INF-263-Onchain-Build-and-Test
        with:
          alchemy_key: ${{ secrets.ALCHEMY_KEY }}
